title1=input("Введите тему: ")
title2=input("Введите заголовок: ")
title3=input("Введите подзаголовок: ")
Title = [title1, title2, title3]
username=input("Введите Ваше имя: ")
title=input("Введите название заметки: ")
contents=input("Введите описание: ")
statistics=input("Поставьте статус: ")
cteated_date=input("Введите дату начала в формате ДД.ММ.ГГГГ: ")
issue_date=input("Введите дату окончания в формате ДД.ММ.ГГГГ: ")
print(*Title, sep = "\n", end="\n\n")
print("Имя пользователя:", username)
print("Название:", title)
print("Описание:", contents)
print("Статус:", statistics)
print("Дата начала:", cteated_date[:5])
print("Дата окончания:", issue_date[:5])
