username=input("Введите Ваше имя: ")
title=input("Введите название заметки: ")
contents=input("Введите описание: ")
statistics=input("Поставьте статус: ")
cteated_date=input("Введите дату начала в формате ДД.ММ.ГГГГ: ")
issue_date=input("Введите дату окончания в формате ДД.ММ.ГГГГ: ")
print("Имя пользователя:", username)
print("Название:", title)
print("Описание:", contents)
print("Статус:", statistics)
print("Дата начала:", cteated_date[:5])
print("Дата окончания:", issue_date[:5])